"""Extended infrastructure listings — VPS, CDN, DNS, domains, marketplaces."""

from __future__ import annotations

from tools.infrastructure_catalog import InfraListing

EXTRA_LISTINGS: tuple[InfraListing, ...] = (
    # ── More EU VPS ──
    InfraListing(
        "Ionos (1&1)", "https://www.ionos.com", "vps",
        ("Germany", "France", "United States"), ("tunnel_origin", "relay"),
        "mid", ("card", "paypal"),
        "Large EU host; decent for mid-tier tunnel nodes.",
        ("DDoS option", "managed WP"), "ionos.com", 74,
        "VPS → Germany", "AS8560", "premium_vps", ("VLESS", "REALITY"), "from €4/mo", ("FSN", "BER"),
    ),
    InfraListing(
        "HostEurope", "https://www.hosteurope.de", "vps",
        ("Germany",), ("tunnel_origin",),
        "mid", ("card", "sepa"),
        "German brand; stable for EU exit.",
        ("KVM", "support DE"), "hosteurope.de", 71,
        "VPS bestellen", "AS34011", "budget_vps", ("VLESS",), "from €5/mo", ("DE",),
    ),
    InfraListing(
        "Strato", "https://www.strato.de", "vps",
        ("Germany",), ("tunnel_origin",),
        "budget", ("card", "sepa"),
        "Budget DE hosting; verify latency before scale.",
        ("VServer",), "strato.de", 68,
        "VServer", "AS6724", "budget_vps", ("VLESS",), "from €3/mo", ("DE",),
    ),
    InfraListing(
        "M247", "https://www.m247.com", "vps",
        ("Germany", "Netherlands", "United Kingdom"), ("tunnel_origin", "relay"),
        "mid", ("card",),
        "Carrier-grade network; good for resellers.",
        ("colo", "DDoS"), "m247.com", 75,
        "VPS / dedicated", "AS9009", "colo_vps", ("REALITY", "VLESS"), "custom", ("DE", "NL", "UK"),
    ),
    InfraListing(
        "Worldstream", "https://www.worldstream.com", "bare_metal",
        ("Netherlands",), ("tunnel_origin",),
        "premium", ("card",),
        "NL bare metal; high bandwidth sellers.",
        ("10G ports",), "worldstream.nl", 83,
        "Dedicated servers NL", "AS49981", "bare_metal", ("REALITY",), "custom", ("NL",),
    ),
    InfraListing(
        "TransIP", "https://www.transip.eu", "vps",
        ("Netherlands",), ("tunnel_origin",),
        "mid", ("card", "ideal"),
        "Dutch VPS; AMS routes.",
        ("snapshots",), "transip.eu", 76,
        "Blade VPS", "AS20857", "budget_vps", ("VLESS",), "from €5/mo", ("AMS",),
    ),
    InfraListing(
        "Cherry Servers", "https://www.cherryservers.com", "vps",
        ("Netherlands", "Germany"), ("tunnel_origin",),
        "mid", ("card",),
        "Baltic/EU network; dedicated resources.",
        ("bare metal",), "cherryservers.com", 76,
        "Cloud VPS", "AS59642", "premium_vps", ("REALITY", "VLESS"), "from €6/mo", ("NL", "DE"),
    ),
    InfraListing(
        "Time4VPS", "https://www.time4vps.com", "vps",
        ("Netherlands",), ("tunnel_origin",),
        "budget", ("card", "paypal"),
        "Budget LT/NL routes; benchmark first.",
        ("KVM",), "time4vps.com", 70,
        "Order VPS", "AS16125", "budget_vps", ("VLESS",), "from $4/mo", ("NL",),
    ),
    InfraListing(
        "PhoenixNAP", "https://phoenixnap.com", "vps",
        ("Germany", "United States"), ("tunnel_origin",),
        "premium", ("card",),
        "Enterprise EU/US; stable backbone.",
        ("bare metal",), "phoenixnap.com", 72,
        "Public cloud", "AS36236", "hyperscaler", ("VLESS",), "custom", ("FRA", "US"),
    ),
    InfraListing(
        "Kamatera", "https://www.kamatera.com", "vps",
        ("Germany", "Netherlands", "United States"), ("tunnel_origin", "relay"),
        "mid", ("card", "paypal"),
        "Flexible hourly cloud; many regions.",
        ("hourly", "API"), "kamatera.com", 73,
        "Create server", "AS54913", "hyperscaler", ("VLESS", "REALITY"), "from $4/mo", ("EU", "US"),
    ),
    InfraListing(
        "HostHatch", "https://hosthatch.com", "vps",
        ("Netherlands", "United States"), ("tunnel_origin",),
        "budget", ("card", "crypto"),
        "Budget NVMe; check stock.",
        ("NVMe",), "hosthatch.com", 69,
        "Deploy", "AS63473", "budget_vps", ("VLESS",), "from $5/mo", ("AMS",),
    ),
    InfraListing(
        "Adman", "https://adman.com", "vps",
        ("Netherlands",), ("tunnel_origin",),
        "budget", ("card",),
        "NL budget VPS community pick.",
        ("KVM",), "adman.com", 67,
        "VPS order", "", "budget_vps", ("VLESS",), "from €4/mo", ("NL",),
    ),
    # ── UK / Nordics / TR / UAE ──
    InfraListing(
        "OVH UK", "https://www.ovhcloud.com/en-gb/", "vps",
        ("United Kingdom",), ("tunnel_origin", "relay"),
        "mid", ("card",),
        "London DC; backup EU path.",
        ("DDoS",), "ovh.com", 78,
        "VPS UK", "AS16276", "premium_vps", ("REALITY",), "from £5/mo", ("LON",),
    ),
    InfraListing(
        "Hetzner HEL", "https://www.hetzner.com/cloud", "vps",
        ("Finland",), ("tunnel_origin",),
        "budget", ("card",),
        "Helsinki — strong Irancell path for some routes.",
        ("HEL1", "NVMe"), "hel1.hetzner.com", 90,
        "Cloud → Helsinki", "AS24940", "budget_vps", ("REALITY", "VLESS"), "from €4/mo", ("HEL1",),
    ),
    InfraListing(
        "Natro TR", "https://www.natro.com", "vps",
        ("Turkey",), ("tunnel_origin", "relay"),
        "mid", ("card", "local TR"),
        "Turkish VPS; low RTT, test DPI.",
        ("TR support",), "natro.com", 72,
        "VPS / cloud", "", "budget_vps", ("VLESS",), "TR pricing", ("Istanbul",),
    ),
    InfraListing(
        "Radore TR", "https://www.radore.com", "vps",
        ("Turkey",), ("tunnel_origin", "relay"),
        "mid", ("card",),
        "TR datacenter; relay candidate.",
        ("colo",), "radore.com", 73,
        "Sanal sunucu", "", "colo_vps", ("VLESS",), "custom", ("TR",),
    ),
    InfraListing(
        "UltaHost UAE", "https://ultahost.com", "vps",
        ("United Arab Emirates",), ("relay",),
        "mid", ("card", "crypto"),
        "Middle East relay hop; not primary IR exit.",
        ("Dubai",), "ultahost.com", 68,
        "VPS Dubai", "", "budget_vps", ("relay",), "from $6/mo", ("DXB",),
    ),
    # ── More CDN / DNS ──
    InfraListing(
        "Akamai CDN", "https://www.akamai.com", "cdn",
        ("Global",), ("cdn_front",),
        "premium", ("enterprise",),
        "Enterprise CDN; overkill for most tunnel sellers.",
        ("edge",), "akamai.com", 65,
        "Contact sales", "AS20940", "enterprise_cdn", ("WS",), "enterprise", ("Global",),
    ),
    InfraListing(
        "KeyCDN", "https://www.keycdn.com", "cdn",
        ("Global",), ("cdn_front",),
        "budget", ("card",),
        "Pay-as-you-go CDN; static asset fronts.",
        ("HTTP/2",), "keycdn.com", 68,
        "Create zone", "AS394536", "budget_cdn", (), "from $0.04/GB", ("Global",),
    ),
    InfraListing(
        "CDN77", "https://www.cdn77.com", "cdn",
        ("Global", "Germany"), ("cdn_front",),
        "mid", ("card",),
        "EU POPs; alternative to CF.",
        ("video",), "cdn77.com", 70,
        "CDN setup", "AS60068", "budget_cdn", (), "trial", ("EU",),
    ),
    InfraListing(
        "QUIC.cloud", "https://quic.cloud", "cdn",
        ("Global",), ("cdn_front",),
        "budget", ("card",),
        "LiteSpeed CDN; WordPress decoy sites.",
        ("QUIC",), "quic.cloud", 78,
        "Link domain", "AS13335", "budget_cdn", ("WS",), "free tier", ("Global",),
    ),
    InfraListing(
        "DNSimple", "https://dnsimple.com", "dns",
        ("Global",), ("domain_ssl", "cdn_front"),
        "mid", ("card",),
        "Managed DNS with API; point to CF or origin.",
        ("API", "ANAME"), "dnsimple.com", 72,
        "Add domain", "", "dns_host", (), "from $5/mo", ("Global",),
    ),
    InfraListing(
        "ClouDNS", "https://www.cloudns.net", "dns",
        ("Global",), ("domain_ssl",),
        "budget", ("card", "crypto"),
        "Cheap DNS hosting; secondary NS.",
        ("GeoDNS",), "cloudns.net", 70,
        "Register DNS", "", "dns_host", (), "free tier", ("Global",),
    ),
    InfraListing(
        "HE.net DNS", "https://dns.he.net", "dns",
        ("Global",), ("domain_ssl",),
        "budget", ("free",),
        "Free DNS; reliable secondary NS.",
        ("DNSSEC",), "dns.he.net", 75,
        "Add zone free", "", "dns_host", (), "free", ("Global",),
    ),
    # ── More domains ──
    InfraListing(
        "Google Domains (Squarespace)", "https://domains.squarespace.com", "domain",
        ("Global",), ("domain_ssl",),
        "mid", ("card",),
        "Domains; point NS to Cloudflare after buy.",
        ("privacy",), "domains.google", 80,
        "Search domain", "", "registrar", (), "varies", ("Global",),
    ),
    InfraListing(
        "Dynadot", "https://www.dynadot.com", "domain",
        ("Global",), ("domain_ssl",),
        "budget", ("card", "crypto"),
        "Low-cost TLDs; bulk domain sellers.",
        ("auction",), "dynadot.com", 82,
        "Register", "", "registrar", (), "from $1", ("Global",),
    ),
    InfraListing(
        "Gandi", "https://www.gandi.net", "domain",
        ("Global",), ("domain_ssl",),
        "mid", ("card",),
        "EU registrar; privacy included.",
        ("SSL",), "gandi.net", 79,
        "Buy domain", "", "registrar", (), "from €8/yr", ("Global",),
    ),
    # ── Panel / marketplace ──
    InfraListing(
        "HostBill / WHMCS resellers", "https://lowendtalk.com", "marketplace",
        ("Global",), ("all",),
        "budget", ("varies",),
        "Community reseller threads — verify every IP with IP Scanner.",
        ("forum",), "lowendtalk.com", 50,
        "Browse offers", "", "marketplace", (), "varies", ("Global",),
    ),
    InfraListing(
        "ServerHunter", "https://www.serverhunter.com", "marketplace",
        ("Global",), ("all",),
        "mid", ("n/a",),
        "Search dedicated/VPS by spec and region.",
        ("filters",), "serverhunter.com", 68,
        "Search servers", "", "marketplace", (), "n/a", ("Global",),
    ),
    InfraListing(
        "CloudProviderIndex", "https://www.cloudproviderindex.com", "marketplace",
        ("Global",), ("all",),
        "mid", ("n/a",),
        "Compare cloud providers by region and price.",
        ("index",), "cloudproviderindex.com", 66,
        "Compare", "", "marketplace", (), "n/a", ("Global",),
    ),
    # ── US budget ──
    InfraListing(
        "ColoCrossing", "https://www.colocrossing.com", "vps",
        ("United States",), ("tunnel_origin",),
        "budget", ("card", "paypal"),
        "Budget US; higher IR latency.",
        ("promo",), "colocrossing.com", 60,
        "VPS specials", "AS36352", "budget_vps", ("VLESS",), "from $3/mo", ("US",),
    ),
    InfraListing(
        "Frantech / BuyVM", "https://buyvm.net", "vps",
        ("United States", "Netherlands"), ("tunnel_origin",),
        "budget", ("card", "crypto"),
        "Stock-limited budget KVM.",
        ("DDoS filter",), "buyvm.net", 71,
        "Check stock", "AS53667", "budget_vps", ("VLESS",), "from $3/mo", ("US", "NL"),
    ),
    InfraListing(
        "Oracle Cloud Free", "https://www.oracle.com/cloud/free/", "vps",
        ("Germany", "United States"), ("tunnel_origin",),
        "budget", ("card",),
        "Always-free ARM; hard signup; good for testing.",
        ("ARM free",), "cloud.oracle.com", 70,
        "Free tier", "AS31898", "hyperscaler", ("VLESS",), "free tier", ("EU", "US"),
    ),
)
